language: node_js
node_js:
- node
cache: yarn
script:
- yarn && cat package.json && yarn run build
before_install:
- openssl aes-256-cbc -K $encrypted_e57daae8cbce_key -iv $encrypted_e57daae8cbce_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
addons:
  ssh_known_hosts:
  - 139.159.134.18
after_success:
- chmod 600 ~/.ssh/id_rsa
- ssh ruios@139.159.134.18 -o StrictHostKeyChecking=no 'cd ~/webapp-lover && git
  pull &&  yarn install && yarn run build'
